services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ia_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ia_api
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DRIVER: org.postgresql.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      AI_PROVIDER: ${AI_PROVIDER}
      AI_BASE_URL: ${AI_BASE_URL}
      GROQ_API_KEY: ${GROQ_API_KEY}
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  db-data:
